### ISSUE TITLE
Error in psycopg2

### ISSUE THREAD

**Issue by JonathanGoikhman** [pr0v3rbs/FirmAE#12]
After getting "[*] Completed initializing core docker", I run `sudo ./docker-helper.py -ec "tp-link" "Archer_VR600v1_0.1.0_0.9.1_up_boot\(160217\)_2016-02-17_14.52.21.zip" ` but I get the error 

`Traceback (most recent call last):
  File "/home/asd/Desktop/FirmAE/./docker-helper.py", line 9, in <module>
    import scripts.util as util
  File "/home/asd/Desktop/FirmAE/scripts/util.py", line 4, in <module>
    import psycopg2
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 104
    connection_factory=None, cursor_factory=None, async=False, **kwargs):
                                                  ^
SyntaxError: invalid syntax
`

The arrow is under "async".

**Comment by pr0v3rbs** [comment]
Maybe the `async` syntax error is fixed on the latest psycopg2 version (please check the [issue](https://github.com/psycopg/psycopg2/issues/1063)).
Can you check again by re-initializing the FirmAE docker?
