### ISSUE TITLE
How to find the failed reason to improve the success rate of simulation  

### ISSUE THREAD

**Issue by dalision** [pr0v3rbs/FirmAE#13]
Thank you for your work, it is exciting to use it. For different firmwares, the reasons for  simulation fail processes are different. As your paper mentioned that Boost，Network，NVRAM，watchdog，symlink factosr have been considered to solve the problem. I wonder how to find the fail reason for a new firmware because there still many firmwares couldn't be simulation successfully. By debugging or something else? Looking forward to your reply!

**Comment by 0xdkay** [comment]
Thanks for your interest!

We manually analyzed the failure cases. It may take some time for the analysis for the first time; however, once you analyzed, the analysis knowledge can be applicable to other device versions/families. As shown in our paper, a large portion of failure cases can be similarly handled although many devices are built from diverse vendors.

The key point is that we need to share the analysis experience and extend the knowledge base to build a more scalable system.
