### ISSUE TITLE
Debugging of boot sequence

### ISSUE THREAD

**Issue by test164c** [pr0v3rbs/FirmAE#15]
Running -d allows for debugging of running processes such as web service, but is there a way to debug the booting sequence itself? I notice many online resources attach -s and -S to QEMU and access it from gdb-multiarch vmlinux followed by target remote :1234. When I do this, continuing from gdb is indeed able to control the execution of the kernel (qemu.final.serial.log only gets updated when it is running in gdb), but no symbols are loaded. 

Would like to clarify if it is possible to load the symbols into gdb when debugging so I can add "hbreak start_kernel" and use lx commands. I noticed there are some binaries in the FirmAE/binaries folder, especially the gdb.arm/mips and vmlinux.mips/zImage ones. Could I clarify if these may be used to debug the firmware/get symbols into gdb, or if I need to source for an external symbol file/library? 

Also wondering if it's possible to have a shell into the emulated firmware image while doing this, as run.sh -d doesn't seem to work when I append -s and -S to the QEMU call in scratch/<iid>/run.sh ("OSError: [Errno 113] No route to host"). 

Thank you!

**Comment by pr0v3rbs** [comment]
Thank you for your great question!

I tested `-s -S` flag for the QEMU on emulated firmware, and the `gdb-multiarch` remote successfully connected. And also the hardware breakpoint was work well.

I tested on DIR-868L_fw_revB_2-05b02_eu_multi_20161117.zip firmware which is `armel` architecture, thus I uploaded debuggable `vmlinux.armel` binary on [FirmAE kernel-v4.1 release](https://github.com/pr0v3rbs/FirmAE_kernel-v4.1/releases/tag/v1.0). Please re-run `download.sh` script.

Currently, I added `-s -S` option in `scratch/${IID}/run.sh` script to run the QEMU with kernel debugging mode. I will update the command on main [`run.sh`](https://github.com/pr0v3rbs/FirmAE/blob/master/run.sh) script, soon.

Tested log as below.

```bash
ubuntu64 ~/Desktop/FirmAE master* $ gdb-multiarch -q ./binaries/vmlinux.armel
pwndbg: loaded 174 commands. Type pwndbg [filter] for a list.
pwndbg: created $rebase, $ida gdb functions (can be used with print/break)
Reading symbols from ./binaries/vmlinux.armel...(no debugging symbols found)...done.
pwndbg> target remote:1234

...

pwndbg> hbreak start_kernel
Hardware assisted breakpoint 1 at 0xc05c6958
pwndbg> c
Continuing.
ERROR: Could not find ELF base!
ERROR: Could not find ELF base!
ERROR: Could not find ELF base!

Breakpoint 1, 0xc05c6958 in start_kernel ()

...

 ► 0xc05c6958 <start_kernel>       push   {r4, r5, r6, r7, r8, sb, lr}
   0xc05c695c <start_kernel+4>     sub    sp, sp, #__vectors_start+28 <28>
   0xc05c6960 <start_kernel+8>     ldr    r0, [pc, #0x2fc]
   0xc05c6964 <start_kernel+12>    bl     #set_task_stack_end_magic <0xc0022994>

   0xc05c6968 <start_kernel+16>    bl     #smp_setup_processor_id <0xc05c942c>

   0xc05c696c <start_kernel+20>    cpsid  i
   0xc05c6970 <start_kernel+24>    ldr    r7, [pc, #0x2f0]
   0xc05c6974 <start_kernel+28>    mov    r4, #1
   0xc05c6978 <start_kernel+32>    mov    r1, r4
   0xc05c697c <start_kernel+36>    mov    r0, #0
   0xc05c6980 <start_kernel+40>    mvn    r6, #0

...

pwndbg>
```

Thank you!
