### ISSUE TITLE
Recompilation of libnvram.so

### ISSUE THREAD

**Issue by test164c** [pr0v3rbs/FirmAE#18]
Hi, I would like to recompile libnvram.so to try a few things. May I know which are the versions of cross-compilers that FirmAE used to compile the libnvram.so? 

Thank you!

**Comment by pr0v3rbs** [comment]
The FirmAE uses firmadyne's cross-compilers [musl-libc](https://github.com/firmadyne/firmadyne#toolchain) for 32bit binaries.

Currently ready to 64bit binaries with [musl-cross-make](https://github.com/richfelker/musl-cross-make).
