### ISSUE TITLE
can not download binary files

### ISSUE THREAD

**Issue by newthis** [pr0v3rbs/FirmAE#2]
Unable to download the binary files required in makeImage.sh file. It seems that those files
can not be downloaded from https://github.com/pr0v3rbs/FirmAE/releases/tag/v1.0 manually,
only the source code can be downloaded.

**Comment by pr0v3rbs** [comment]
Maybe this issue already resolved in the #1

And with my mistake, I force pushed `Initial commit` 854a41c8688c3b68ff89a363fc51e726fb9ec950 after you forked.

So, if your forked repository can't sync with this upstream/master repository, then I suggest that re-fork this repository again. Sorry about that.

**Comment by newthis** [comment]
it is ok now.
