### ISSUE TITLE
Mounting /dev/loop3p1 already mounted

### ISSUE THREAD

**Issue by docfate111** [pr0v3rbs/FirmAE#23]
How do I unmount an image? I can't connect to the IP even though the script says network and web service reachable. I can't see mount anywhere in run.sh
The error is 
```
sudo ./run.sh -a netgear firmwares/firm
mount: FirmAE/scratch/4/image: /dev/loop3p1 already mount on FirmAE/scratch/4/image
None false false -1 -1 
None false false -1 -1 
```

**Comment by waiwai24** [comment]
can you tell me how do you solve this problem？I also have same problem.

```

user@ubuntu:~/Desktop/FirmAE$ sudo ./run.sh -r h3c ./firmwares/SWBR1A0V100R004.bin 
[*] ./firmwares/SWBR1A0V100R004.bin emulation start!!!
[*] extract done!!!
[*] get architecture done!!!
[*] ./firmwares/SWBR1A0V100R004.bin already succeed emulation!!!

[IID] 7
[MODE] run
[+] Network reachable on 192.168.0.1!
[+] Web service on 192.168.0.1
mount: /home/user/Desktop/FirmAE/scratch/7/image: /dev/loop18p1 already mounted on /home/user/Desktop/FirmAE/scratch/7/image.


```

**Comment by waiwai24** [comment]
> @docfate111 can you tell me how do you solve this problem？I also have same problem.thank you!
> 
> ```
> 
> user@ubuntu:~/Desktop/FirmAE$ sudo ./run.sh -r h3c ./firmwares/SWBR1A0V100R004.bin 
> [*] ./firmwares/SWBR1A0V100R004.bin emulation start!!!
> [*] extract done!!!
> [*] get architecture done!!!
> [*] ./firmwares/SWBR1A0V100R004.bin already succeed emulation!!!
> 
> [IID] 7
> [MODE] run
> [+] Network reachable on 192.168.0.1!
> [+] Web service on 192.168.0.1
> mount: /home/user/Desktop/FirmAE/scratch/7/image: /dev/loop18p1 already mounted on /home/user/Desktop/FirmAE/scratch/7/image.
> ```
