### ISSUE TITLE
Mounted error

### ISSUE THREAD

**Issue by JonathanGoikhman** [pr0v3rbs/FirmAE#31]
Hello, First of all thank you for the great project. 

After all the setup process, when I run the command `sudo ./run.sh -r dlink /home/iot/Desktop/DIR823A1_FW100WWb05.bin `

I get these lines: 
`[*] /home/iot/Desktop/DIR823A1_FW100WWb05.bin emulation start!!!
[*] extract done!!!
[*] get architecture done!!!
mke2fs 1.44.1 (24-Mar-2018)
/dev/loop3p1 is mounted; will not make a filesystem here!
`
Do you have any idea how can I fix the problem?
Thank you!

**Comment by pr0v3rbs** [comment]
Thank you for your interest!

It seems to another firmware emulation fails while mounting the filesystem. Thus, the mounted filesystem was mismatched.

You can find the already mounted filesystem by `losetup` command.
Go to the emulation-failed `scratch` directory, unmount the filesystem with `umount image` command. Then, remove the partition device with `kpartx -d image.raw`.

**Comment by 0xdkay** [comment]
I cannot get the exact cause from the posted error message, but trying `sudo losetup -D` to release loop devices as @pr0v3rbs said.

**Comment by YB1-cyber** [comment]
@pr0v3rbs 

I Released the loop devices. i unmounted + deleted the folder '/FirmAE/scratch/1'
run again a new is created and I still get this error:
`# ./run.sh -d tplink /root/Desktop/firmware/DIR880A1_FW107WWb08.bin`
[*] /root/Desktop/firmware/DIR880A1_FW107WWb08.bin emulation start!!!
[*] extract done!!!
[*] get architecture done!!!
mke2fs 1.46.4 (18-Aug-2021)
e2fsck 1.46.4 (18-Aug-2021)
e2fsck: Cannot continue, aborting.

**Comment by pr0v3rbs** [comment]
@YB1-cyber
Can you try again after runs the command? (`sudo losetup -D`)

**Comment by Ryze-T** [comment]
<img width="868" alt="image" src="https://user-images.githubusercontent.com/76553352/169677391-a52cf3f7-8ea5-491b-ad0c-e5ee2c1e0fa1.png">

The Problem still exist
