### ISSUE TITLE
Firmware repository

### ISSUE THREAD

**Issue by attilaszia** [pr0v3rbs/FirmAE#32]
Hi,

awesome research. Are you planning to publish the collected firmwares that this was ran on or at least the URI's (maybe script) that can be used to scrape them? E.g: AnalysisSet, LatestSet,CamSet?
Alternatively, any tip on how to collect such a repo of fw's or a pointer to similar projects would be appreciated.

Best regards,
Attila

**Comment by 0xdkay** [comment]
Hi Attila, thanks for your interest.

We already provide the dataset. Please check [Readme](https://github.com/pr0v3rbs/FirmAE#dataset).

To collect the dataset, we ran [scraper](https://github.com/pr0v3rbs/FirmAE/tree/master/sources/scraper), which is the same as Firmadyne's. Most vendors (at least the ones in our experiment) provide their firmware images through their websites, so one can download them manually or run scripts (as in our case) to crawl them.

Dongkwan
