### ISSUE TITLE
Binwalk corrupts symlinks

### ISSUE THREAD

**Issue by alexsantee** [pr0v3rbs/FirmAE#39]
I've installed FirmAE on a Linux Mint 20.1 which already had binwalk installed. I've used the build.sh and install.sh scripts, but I'm not sure if FirmAE is using the system's Binwalk or if it's using another.

At extraction binwalk shows this warning message of converting an external symlink to /dev/null, which I think is bad for the emulation:

```
WARNING: Symlink points outside of the extraction directory: /tmp/tmpbeeef6ux/_openwrt-21.02.1-ramips-mt76x8-tplink_tl-wr840n-v4-squashfs-sysupgrade.bin.extracted/squashfs-root/sbin/modinfo -> /usr/sbin/kmodloader; changing link target to /dev/null for security purposes.
```

In a chroot or emulated environment this security risk shouldn't apply

Currently I'm using the `--preserve-symlinks` flag for binwalk at the extractor script

**Comment by pr0v3rbs** [comment]
This issue was fixed in [6911f56](https://github.com/pr0v3rbs/FirmAE/commit/6911f56d92937b0d30bb58ab36d622c31a97a1ee)
