### ISSUE TITLE
D-Link：network simulation problem

### ISSUE THREAD

**Issue by foxcookie** [pr0v3rbs/FirmAE#41]
Hello,
I'm having some network emulation issues when using FirmAE to emulate the D-Link firmware, I can't get the IP address.
![image](https://user-images.githubusercontent.com/52572983/164386249-5870b0c9-a8c4-4515-91be-8e7d6e49c0c4.png)

**Comment by Re1own** [comment]
So do I!!

**Comment by foxcookie** [comment]
> 我也是，但是5分钟后，出现ip地址（192.168.0.1）然后访问ip，就可以了！ <img alt="图片" width="1792" src="https://user-images.githubusercontent.com/51265145/168119742-c0861ad9-a4ba-4c40-95aa-045965c0610f.png">

Thank youThe problem has been solved, as you said.
