### ISSUE TITLE
./run.sh stuck on "infer network start!!!"

### ISSUE THREAD

**Issue by wrinklykong** [pr0v3rbs/FirmAE#66]
Hello, new user here, I can't seem to get any firmware to get past the "infer network start!!!" message. I ran the download/install/init bash scripts and tried running it in docker as well and neither worked. I've tested it with the test firmware in the README, as well as other firmware binaries and none seem to boot up.

I am running Ubuntu 18.04 inside VM Virtualbox on a newly created VM.

Commands ran:
```
$ sudo ./run.sh -c dlink DIR-868L_fw_revB_2-05b02_eu_multi_20161117.zip 
[*] DIR-868L_fw_revB_2-05b02_eu_multi_20161117.zip emulation start!!!
[*] extract done!!!
[*] get architecture done!!!
mke2fs 1.44.1 (24-Mar-2018)
e2fsck 1.44.1 (24-Mar-2018)
[*] infer network start!!!
```

Am I missing something? Thanks :)

Edit: As soon as I commented this, it worked. For future reference, I would appreciate to know why this happen. Thanks!

**Comment by whhomi** [comment]
you can try to read the file named  `makeNetwork.log`
