### ISSUE TITLE
ERROR: Could not build wheels for python-lzo, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by zer0-1s** [pr0v3rbs/FirmAE#67]
![image](https://github.com/pr0v3rbs/FirmAE/assets/62493040/45bcd260-cb4d-47ac-bf31-98722ed012e0)

kali info 
![image](https://github.com/pr0v3rbs/FirmAE/assets/62493040/7cdf7aca-0857-46a6-b8cb-687b184428bf)

**Comment by pr0v3rbs** [comment]
What kind of Linux do you use? Currently, FirmAE supports Ubuntu 18.04, 20.04.

**Comment by pr0v3rbs** [comment]
Please install liblzo2-dev package.
